# Generated by Django 4.2.7 on 2023-11-15 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelli', '0002_task_priority_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 6, 18, 34, 816102)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 6, 18, 34, 816102)),
        ),
    ]
