# Generated by Django 4.2.7 on 2023-11-15 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelli', '0003_task_created_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 0, 50, 28, 321356, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 0, 50, 28, 321356, tzinfo=datetime.timezone.utc)),
        ),
    ]
