# Generated by Django 4.2.7 on 2023-11-16 09:34

from django.db import migrations, models
import intelli.models


class Migration(migrations.Migration):

    dependencies = [
        ('intelli', '0004_alter_task_created_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=intelli.models.currTime),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=intelli.models.currTime),
        ),
    ]
